name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:mac

      - name: Web unit tests
        run: yarn test-unit:web

      - name: Node unit tests
        run: yarn test-unit:node

      - name: Node integration tests
        run: yarn test-integration:node

      - name: Web integration tests
        run: yarn test-integration:web

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unsupported OS
        run: echo "Windows builds are not currently supported."

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unsupported OS
        run: echo "Linux builds are not currently supported."

  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Format code
        run: yarn format

      - name: Lint code
        run: yarn lint

      - name: Typecheck Node
        run: yarn typecheck:node

      - name: Typecheck Web
        run: yarn typecheck:web
